import os
import pandas as pd
import json
import openai
from dotenv import load_dotenv

# 載入環境變數 (您的 .env 檔案應該有 OPENAI_API_KEY)
load_dotenv()
openai_key = os.getenv("OPENAI_API_KEY")

if not openai_key:
    raise ValueError("找不到 OPENAI_API_KEY，請確認您的 .env 檔案設定。")

client = openai.OpenAI(api_key=openai_key)

# 1. 讀取現有的主題關鍵字檔案
INPUT_CSV = "output_specter2_3000/topic_keywords.csv"
OUTPUT_CSV = "output_specter2_3000/topic_macro_groups.csv"
OUTPUT_JSON = "output_specter2_3000/macro_mapping.json"

print(f"正在讀取 {INPUT_CSV} ...")
df_topics = pd.read_csv(INPUT_CSV)

# 排除可能有的雜訊主題 (-1)
if -1 in df_topics['Topic_ID'].values:
    df_topics = df_topics[df_topics['Topic_ID'] != -1]

# 2. 組合要餵給 LLM 的內容
topic_descriptions = []
for index, row in df_topics.iterrows():
    topic_id = row['Topic_ID']
    label = row['English_Label']
    keywords = row['Top10_Keywords']
    topic_descriptions.append(f"Topic_ID: {topic_id} | Label: {label} | Keywords: {keywords}")

topics_text = "\n".join(topic_descriptions)

# 3. 撰寫英文 Prompt
# 要求 LLM 扮演專家，將主題收斂成 6 大類，並以 JSON 格式回傳
system_prompt = """
You are a domain expert in the steel industry, metallurgy, and carbon neutrality technologies.
Below is a list of ALL sub-topics generated by a topic modeling algorithm from a dataset of steel carbon neutrality patents.
Each sub-topic includes a Topic_ID, an English Label, and the Top 10 Keywords.

Your task is to logically group ALL of these sub-topics into EXACTLY one of the following 6 predefined Macro-Topics (Major Technology Domains):

[ALLOWED MACRO-TOPICS]
1. "Hydrogen Metallurgy and Direct Reduction" (includes DRI, sponge iron, hydrogen use)
2. "Electric Arc Furnace and Scrap Recycling" (includes EAF, scrap preheating, recycling)
3. "Waste Heat and Energy Recovery" (includes heat recovery, off-gas energy recycling)
4. "Slag and Solid Waste Valorization" (includes slag recycling, dust, metal extraction from waste)
5. "Blast Furnace and Process Optimization" (includes BOF/BF efficiency, hot blast, general ironmaking)
6. "Carbon Capture and Alternative Reductants" (includes CCUS, biomass, carbon sequestration)

Please assign EVERY SINGLE Topic_ID to one of the 6 Macro-Topics listed above. Do NOT invent new Macro-Topic names.

You MUST output ONLY a valid JSON dictionary where the key is the "Topic_ID" (as a string) and the value is the EXACT name of the assigned Macro-Topic from the list above. 
CRITICAL: The output JSON MUST contain a key for EVERY Topic_ID provided in the input (from "0" up to the last one). Do not stop early.

Example Output Format:
{
  "0": "Slag and Solid Waste Valorization",
  "1": "Slag and Solid Waste Valorization",
  "2": "Waste Heat and Energy Recovery",
  ...
  "68": "Carbon Capture and Alternative Reductants"
}
"""

user_prompt = f"Here are the sub-topics to be grouped:\n\n{topics_text}"

# 4. 呼叫 OpenAI API
print("正在呼叫 OpenAI API 進行語意收斂分類，請稍候...")
response = client.chat.completions.create(
    model="gpt-4o-mini", # 這裡使用 gpt-4o 確保分類邏輯的品質最高
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ],
    temperature=0.2 # 溫度設低一點，確保結果穩定
)

result_text = response.choices[0].message.content.strip()

# 清理可能被 GPT 加上去的 markdown 標籤
if result_text.startswith("```json"):
    result_text = result_text[7:]
if result_text.endswith("```"):
    result_text = result_text[:-3]
result_text = result_text.strip()

# 5. 解析 JSON 並儲存結果
try:
    mapping_dict = json.loads(result_text)
    
    # 儲存 mapping dict 為 JSON
    with open(OUTPUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(mapping_dict, f, indent=4, ensure_ascii=False)
    print(f"\n✅ 成功生成對應字典，已儲存至: {OUTPUT_JSON}")
    
    # 將大分類映射回原本的 DataFrame
    df_topics['Macro_Topic'] = df_topics['Topic_ID'].astype(str).map(mapping_dict)
    
    # 儲存帶有大分類的新 CSV
    df_topics.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
    print(f"✅ 成功將結果整合，已儲存至: {OUTPUT_CSV}")
    
    print("\n【分類預覽】:")
    for macro_topic in df_topics['Macro_Topic'].unique():
        count = len(df_topics[df_topics['Macro_Topic'] == macro_topic])
        print(f" - {macro_topic}: 包含 {count} 個子主題")

except json.JSONDecodeError as e:
    print("❌ JSON 解析失敗，LLM 可能回傳了非預期的格式。")
    print("LLM 原始回覆:")
    print(result_text)
