import re

with open('BERTopic_specter2.py', 'r') as f:
    content = f.read()

# 1. Find the start of stage8_hierarchical_grouping
start_marker = "def stage8_hierarchical_grouping("
end_marker = "# =============================================================================\n# STAGE 7：Topics over Time 動態主題分析\n# ============================================================================="

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print("Could not find start or end markers for stage 8 function.")
    exit(1)

new_functions = """def _llm_regroup_topics(
    initial_mapping_df,
    model="gpt-4o-mini",
):
    \"\"\"
    Use LLM to refine topic-to-group assignment based on Topic_ID,
    Doc_Count, Top10_Keywords, and initial hierarchical clustering results.

    Returns a DataFrame with:
    Topic_ID, Final_Group_Name, Reason
    \"\"\"
    from openai import OpenAI
    import json
    import re

    api_key = _load_openai_key()
    client = OpenAI(api_key=api_key)

    topic_lines = []
    for _, row in initial_mapping_df.sort_values("Topic_ID").iterrows():
        topic_lines.append(
            f"Topic {int(row['Topic_ID'])} | "
            f"Initial_Group_ID: {int(row['Group_ID'])} | "
            f"Initial_Group_Name: {row['Group_Name']} | "
            f"Doc_Count: {int(row['Doc_Count'])} | "
            f"Top10_Keywords: {row['Top10_Keywords']}"
        )

    topics_text = "\\n".join(topic_lines)

    prompt = (
        "You are an expert in steel industry decarbonization technologies and patent topic analysis.\\n\\n"
        "The following table contains BERTopic fine-grained topics from steel industry carbon-neutrality patents. "
        "Each topic has a Topic_ID, document count, Top-10 keywords, and an initial group generated by "
        "Ward hierarchical clustering on normalized topic embeddings.\\n\\n"
        "Your task is to refine the topic-to-group assignment. "
        "Use the initial group only as a reference. Do not simply follow it if the technical meaning is inconsistent.\\n\\n"
        "Grouping rules:\\n"
        "1. Group topics by steelmaking decarbonization technology pathway, not by generic words.\\n"
        "2. Do not merge topics only because they share generic terms such as gas, furnace, steel, heat, carbon, slag, or reduction.\\n"
        "3. Carefully distinguish the following contexts:\\n"
        "   - blast furnace gas, hot blast, tuyere, blast furnace stove: Blast Furnace Gas and Energy Management\\n"
        "   - electric arc furnace, electrode, arc furnace, scrap, scrap preheating, slag foaming: Electric Arc Furnace and Scrap Recycling\\n"
        "   - steel slag, furnace slag, blast furnace slag, red mud, sludge, aqueous extraction: Slag and By-product Utilization\\n"
        "   - direct reduction, reducing gas, hydrogen gas, shaft furnace, fluidized bed reduction, DRI, sponge iron, hot briquetted iron: Direct Reduction and Hydrogen Metallurgy\\n"
        "   - carbon dioxide, carbon monoxide, exhaust gas, waste gas, flue gas, syngas, process gas: CCUS and Process Gas Utilization\\n"
        "   - molten steel composition, denitrification, deoxidation, ladle treatment: Metallurgical Treatment and Composition Control\\n"
        "   - pig iron, molten iron, melting DRI product, electrical smelting: Pig Iron and Molten Iron Production\\n"
        "   - molten carbonate fuel cells: Molten Carbonate Fuel Cells\\n"
        "4. Assign every Topic_ID to exactly one final technology group.\\n"
        "5. Use concise English group names suitable for academic tables.\\n"
        "6. Do not invent technical content not supported by the keywords.\\n"
        "7. Prefer 6 to 10 final groups. It is acceptable to use fewer or more only if technically necessary.\\n\\n"
        "Required output format:\\n"
        "Return valid JSON only. Do not add markdown, comments, or explanation outside JSON.\\n"
        "Return a JSON array. Each item must contain:\\n"
        "- Topic_ID: integer\\n"
        "- Final_Group_Name: string\\n"
        "- Reason: string\\n\\n"
        "Topics to classify:\\n\\n"
        + topics_text
    )

    print("\\nCalling LLM to refine topic-to-group assignments...")
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=4000,
    )

    raw = response.choices[0].message.content.strip()
    print(f"LLM regrouping response:\\n{raw}\\n")

    raw_clean = re.sub(r"^```json\\s*", "", raw)
    raw_clean = re.sub(r"^```\\s*", "", raw_clean)
    raw_clean = re.sub(r"\\s*```$", "", raw_clean)

    try:
        data = json.loads(raw_clean)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Failed to parse LLM JSON output: {e}\\nRaw output:\\n{raw}")

    import pandas as pd
    final_df = pd.DataFrame(data)

    required_cols = {"Topic_ID", "Final_Group_Name", "Reason"}
    missing = required_cols - set(final_df.columns)
    if missing:
        raise ValueError(f"LLM output missing required columns: {missing}")

    final_df["Topic_ID"] = final_df["Topic_ID"].astype(int)

    return final_df


def build_final_group_mapping(
    initial_mapping_df,
    llm_final_df,
    output_dir,
):
    \"\"\"
    Merge LLM-refined topic grouping with initial mapping and assign Final_Group_ID.
    \"\"\"
    import pandas as pd
    final_mapping_df = initial_mapping_df.merge(
        llm_final_df,
        on="Topic_ID",
        how="left"
    )

    if final_mapping_df["Final_Group_Name"].isna().any():
        missing_topics = final_mapping_df[
            final_mapping_df["Final_Group_Name"].isna()
        ]["Topic_ID"].tolist()
        raise ValueError(f"Missing Final_Group_Name for topics: {missing_topics}")

    group_names = sorted(final_mapping_df["Final_Group_Name"].unique())
    group_name_to_id = {name: idx for idx, name in enumerate(group_names)}

    final_mapping_df["Final_Group_ID"] = final_mapping_df["Final_Group_Name"].map(
        group_name_to_id
    )

    final_mapping_df = final_mapping_df[
        [
            "Topic_ID",
            "Doc_Count",
            "Top10_Keywords",
            "Group_ID",
            "Group_Name",
            "Final_Group_ID",
            "Final_Group_Name",
            "Reason",
        ]
    ].sort_values(["Final_Group_ID", "Topic_ID"])

    final_mapping_df.to_csv(
        output_dir / "final_group_topic_mapping.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("Final topic-to-group mapping saved:")
    print("  └── final_group_topic_mapping.csv")

    return final_mapping_df


def apply_final_groups_to_patents(
    df,
    final_mapping_df,
    output_dir,
):
    \"\"\"
    Apply LLM-refined final technology groups to patent-level dataframe.
    \"\"\"

    topic_to_final_group_id = dict(zip(
        final_mapping_df["Topic_ID"],
        final_mapping_df["Final_Group_ID"]
    ))

    topic_to_final_group_name = dict(zip(
        final_mapping_df["Topic_ID"],
        final_mapping_df["Final_Group_Name"]
    ))

    df = df.copy()

    df["final_group_id"] = df["topic_id"].map(
        lambda t: topic_to_final_group_id.get(t, -1)
    )

    df["final_group_name"] = df["topic_id"].map(
        lambda t: topic_to_final_group_name.get(t, "NOISE") if t != -1 else "NOISE"
    )

    df.to_parquet(
        output_dir / "patent_with_final_topic_groups.parquet",
        index=False
    )

    df.to_csv(
        output_dir / "patent_with_final_topic_groups.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("Patent-level final group file saved:")
    print("  ├── patent_with_final_topic_groups.parquet")
    print("  └── patent_with_final_topic_groups.csv")

    return df


def stage8_final_group_evolution(
    df,
    output_dir,
):
    \"\"\"
    Run technology-group-level evolution analysis using LLM-refined final groups.
    \"\"\"
    import pandas as pd
    import numpy as np
    print("=" * 60)
    print("STAGE 8E: Final technology-group-level evolution analysis")
    print("=" * 60)

    SEGMENTS = [
        "SEG_A_2006_2010",
        "SEG_B_2011_2015",
        "SEG_C_2016_2020",
        "SEG_D_2021_2025",
    ]

    group_df = df[df["final_group_id"] != -1].copy()
    group_df["priority_year"] = group_df["priority_date"].dt.year

    g_seg_counts = pd.crosstab(
        group_df["final_group_name"],
        group_df["time_segment"]
    )
    g_seg_counts = g_seg_counts.reindex(columns=SEGMENTS, fill_value=0)

    g_seg_counts.to_csv(
        output_dir / "final_group_segment_counts.csv",
        encoding="utf-8-sig"
    )

    seg_totals = group_df["time_segment"].value_counts().reindex(SEGMENTS, fill_value=0)
    g_seg_shares = g_seg_counts.div(
        seg_totals.replace(0, np.nan),
        axis=1
    ).fillna(0)

    g_seg_shares.to_csv(
        output_dir / "final_group_segment_shares.csv",
        encoding="utf-8-sig"
    )

    g_yearly_counts = pd.crosstab(
        group_df["priority_year"],
        group_df["final_group_name"]
    )
    g_yearly_counts = g_yearly_counts.reindex(range(2006, 2026), fill_value=0)

    g_yearly_counts.to_csv(
        output_dir / "final_group_yearly_counts.csv",
        encoding="utf-8-sig"
    )

    g_yearly_totals = g_yearly_counts.sum(axis=1).replace(0, np.nan)
    g_yearly_shares = g_yearly_counts.div(g_yearly_totals, axis=0).fillna(0)

    g_yearly_shares.to_csv(
        output_dir / "final_group_yearly_shares.csv",
        encoding="utf-8-sig"
    )

    segment_midpoints = np.array([2008, 2013, 2018, 2023], dtype=float)

    rows = []

    for group_name in g_seg_counts.index:
        freq = [int(g_seg_counts.loc[group_name, s]) for s in SEGMENTS]
        shares = [float(g_seg_shares.loc[group_name, s]) for s in SEGMENTS]

        slope = float(np.polyfit(segment_midpoints, shares, 1)[0])
        peak_idx = int(np.argmax(freq))

        early = sum(freq[:2])
        late = sum(freq[2:])
        growth = (late - early) / (early + 1)

        trajectory = classify_trajectory(freq, shares)

        rows.append({
            "Final_Group_Name": group_name,
            "Doc_Count": sum(freq),
            "Freq_2006_2010": freq[0],
            "Freq_2011_2015": freq[1],
            "Freq_2016_2020": freq[2],
            "Freq_2021_2025": freq[3],
            "Share_2006_2010": round(shares[0], 4),
            "Share_2011_2015": round(shares[1], 4),
            "Share_2016_2020": round(shares[2], 4),
            "Share_2021_2025": round(shares[3], 4),
            "Share_Change": round(shares[-1] - shares[0], 4),
            "Share_Slope_Per_Year": round(slope, 6),
            "Growth_Rate": round(growth, 3),
            "Peak_Segment": SEGMENTS[peak_idx],
            "Trajectory": trajectory,
        })

    final_group_evo_df = pd.DataFrame(rows).sort_values(
        "Doc_Count",
        ascending=False
    )

    final_group_evo_df.to_csv(
        output_dir / "final_group_evolution_summary.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("Final group evolution files saved:")
    print("  ├── final_group_segment_counts.csv")
    print("  ├── final_group_segment_shares.csv")
    print("  ├── final_group_yearly_counts.csv")
    print("  ├── final_group_yearly_shares.csv")
    print("  └── final_group_evolution_summary.csv")

    return g_seg_counts, g_seg_shares, final_group_evo_df


def stage8_initial_grouping_and_llm_regrouping(
    topic_model,
    df,
    abstracts,
    keywords_df,
    n_groups=12,
    interactive=True,
):
    \"\"\"
    STAGE 8:
    1. Generate initial technology groups using Ward clustering on normalized topic embeddings.
    2. Use LLM to semantically regroup topics into final technology groups.
    3. Apply final groups to patent-level data.
    4. Run final group-level evolution analysis.
    \"\"\"
    import pandas as pd
    import numpy as np
    from scipy.cluster.hierarchy import linkage, fcluster
    
    print("=" * 60)
    print("STAGE 8: Initial clustering + LLM semantic regrouping")
    print("=" * 60)

    output_dir = OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Step 1：Extract topic embeddings ─────────────────────────────
    topic_ids = sorted([t for t in set(topic_model.topics_) if t != -1])
    n_topics = len(topic_ids)
    print(f"\\nFine-grained topics: {n_topics}")

    all_embs = topic_model.topic_embeddings_
    outlier_offset = getattr(topic_model, "_outliers", 0)

    topic_embs = np.array([
        all_embs[tid + outlier_offset]
        for tid in topic_ids
    ])

    print(f"Raw topic embedding shape: {topic_embs.shape}")

    # ── Step 2：Initial Ward clustering ──────────────────────────────
    from sklearn.preprocessing import normalize

    topic_embs_norm = normalize(topic_embs, norm="l2")

    Z = linkage(topic_embs_norm, method="ward", metric="euclidean")

    cluster_labels = fcluster(Z, t=n_groups, criterion="maxclust")

    unique_labels = sorted(set(cluster_labels))
    label_map = {old: new for new, old in enumerate(unique_labels)}
    cluster_labels = np.array([label_map[x] for x in cluster_labels])

    n_groups = len(unique_labels)
    topic_to_group = dict(zip(topic_ids, cluster_labels))

    print(f"\\nInitial clustering produced {n_groups} groups:")
    for gid in range(n_groups):
        members = [t for t, g in topic_to_group.items() if g == gid]
        print(f"  Initial Group {gid}: Topic {members}")

    group_sizes = pd.Series(cluster_labels).value_counts().sort_index()
    print("\\nInitial group size summary:")
    for gid, size in group_sizes.items():
        print(f"  Initial Group {gid}: {size} topics")

    # Save linkage matrix
    linkage_df = pd.DataFrame(
        Z,
        columns=["Cluster_1", "Cluster_2", "Distance", "Sample_Count"]
    )
    linkage_df.to_csv(
        output_dir / "topic_hierarchical_linkage.csv",
        index=False,
        encoding="utf-8-sig"
    )

    # ── Step 3：Prepare initial mapping ──────────────────────────────
    keyword_map = dict(zip(keywords_df["Topic_ID"], keywords_df["Top10_Keywords"]))
    count_map = dict(zip(keywords_df["Topic_ID"], keywords_df["Doc_Count"]))

    # First use LLM only to name initial groups
    group_info = []
    for gid in range(n_groups):
        members = [t for t, g in topic_to_group.items() if g == gid]
        topics_detail = []
        total_docs = 0

        for tid in members:
            doc_count = int(count_map.get(tid, 0))
            total_docs += doc_count
            topics_detail.append({
                "Topic_ID": tid,
                "Doc_Count": doc_count,
                "Top10_Keywords": keyword_map.get(tid, ""),
            })

        group_info.append({
            "group_id": gid,
            "total_docs": total_docs,
            "topics": topics_detail,
        })

    try:
        initial_group_names = _llm_name_groups(group_info)
    except Exception as e:
        print(f"\\n⚠ Initial group naming failed ({e}), using default names")
        initial_group_names = {gid: f"InitialGroup_{gid}" for gid in range(n_groups)}

    for gid in range(n_groups):
        if gid not in initial_group_names:
            initial_group_names[gid] = f"InitialGroup_{gid}"

    initial_rows = []
    for tid in topic_ids:
        gid = topic_to_group[tid]
        initial_rows.append({
            "Topic_ID": tid,
            "Group_ID": gid,
            "Group_Name": initial_group_names[gid],
            "Doc_Count": int(count_map.get(tid, 0)),
            "Top10_Keywords": keyword_map.get(tid, ""),
        })

    initial_mapping_df = pd.DataFrame(initial_rows).sort_values("Topic_ID")

    initial_mapping_df.to_csv(
        output_dir / "initial_group_topic_mapping.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\\nInitial group mapping saved:")
    print("  └── initial_group_topic_mapping.csv")

    # ── Step 4：LLM semantic regrouping ──────────────────────────────
    llm_final_df = _llm_regroup_topics(initial_mapping_df)

    llm_final_df.to_csv(
        output_dir / "llm_final_grouping_raw.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("Raw LLM final grouping saved:")
    print("  └── llm_final_grouping_raw.csv")

    # ── Step 5：Build final mapping ─────────────────────────────────
    final_mapping_df = build_final_group_mapping(
        initial_mapping_df,
        llm_final_df,
        output_dir
    )

    print("\\nFinal topic grouping:")
    for group_name, sub_df in final_mapping_df.groupby("Final_Group_Name"):
        topics = sub_df["Topic_ID"].tolist()
        docs = sub_df["Doc_Count"].sum()
        print(f"  {group_name} ({docs} docs): Topic {topics}")

    # ── Step 6：Apply final groups to patent-level dataframe ─────────
    df_final = apply_final_groups_to_patents(
        df,
        final_mapping_df,
        output_dir
    )

    # ── Step 7：Final group-level evolution analysis ────────────────
    g_seg_counts, g_seg_shares, final_group_evo_df = stage8_final_group_evolution(
        df_final,
        output_dir
    )

    print("\\nSTAGE 8 completed\\n")

    return df_final, initial_mapping_df, final_mapping_df, final_group_evo_df
\n"""

# Replace stage8 code
new_content = content[:start_idx] + new_functions + content[end_idx:]

# Replace main block
old_main = """    # STAGE 8：階層式技術群歸併 + LLM 命名 + 群層級演進
    df, mapping_df, group_evo_df, group_names = stage8_hierarchical_grouping(
        topic_model, df, abstracts, keywords_df,
        n_groups=12,
        interactive=True,
    )

    print("=" * 60)
    print("全流程執行完畢")
    print(f"最終 DataFrame 欄位：{list(df.columns)}")
    print("輸出目錄：/home/carbon/carbon/output_specter2/")
    print("  ├── patent_with_topics.parquet")
    print("  ├── topic_keywords.csv")
    print("  ├── topics_over_time.csv")
    print("  ├── topic_lifecycle.csv")
    print("  ├── topic_evolution_summary.csv")
    print("  ├── topic_yearly_counts.csv / topic_yearly_shares.csv")
    print("  ├── group_topic_mapping.csv")
    print("  ├── topic_hierarchical_linkage.csv")
    print("  ├── group_segment_counts/shares.csv")
    print("  ├── group_yearly_counts/shares.csv")
    print("  └── group_evolution_summary.csv")
    print("=" * 60)"""

new_main = """    # STAGE 8: Initial clustering + LLM semantic regrouping
    df_final, initial_mapping_df, final_mapping_df, final_group_evo_df = (
        stage8_initial_grouping_and_llm_regrouping(
            topic_model,
            df,
            abstracts,
            keywords_df,
            n_groups=12,
            interactive=True,
        )
    )

    print("=" * 60)
    print("全流程執行完畢")
    print(f"最終 DataFrame 欄位：{list(df_final.columns)}")
    print("輸出目錄：/home/carbon/carbon/output_specter2/")
    print("  ├── topic_keywords.csv")
    print("  ├── patent_with_topics.parquet")
    print("  ├── topics_over_time.csv")
    print("  ├── topic_lifecycle.csv")
    print("  ├── topic_evolution_summary.csv")
    print("  ├── initial_group_topic_mapping.csv")
    print("  ├── llm_final_grouping_raw.csv")
    print("  ├── final_group_topic_mapping.csv")
    print("  ├── patent_with_final_topic_groups.parquet")
    print("  ├── patent_with_final_topic_groups.csv")
    print("  ├── final_group_segment_counts.csv")
    print("  ├── final_group_segment_shares.csv")
    print("  ├── final_group_yearly_counts.csv")
    print("  ├── final_group_yearly_shares.csv")
    print("  ├── final_group_evolution_summary.csv")
    print("  └── topic_hierarchical_linkage.csv")
    print("=" * 60)"""

new_content = new_content.replace(old_main, new_main)

with open('BERTopic_specter2.py', 'w') as f:
    f.write(new_content)
print("Patch applied.")
